### ISSUE TITLE
Order ID might be repeated

### ISSUE THREAD

**Issue by GnohChengYi** [AY2122S1-CS2103T-W08-3/tp#153]
If the user manually edits the data file to change the Order ID, new Orders created might use existing ID since this is not checked.

**Comment by ngchisern** [comment]
<img width="880" alt="Screenshot 2021-10-30 at 1 54 20 PM" src="https://user-images.githubusercontent.com/64767959/139522208-b223d885-ce81-421b-8147-6569a9211f00.png">
