### ISSUE TITLE
[PE-D] Sortorders2 (multiple prefixes)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#199]
![Screenshot 2021-10-29 at 4.40.42 PM.png](https://raw.githubusercontent.com/willyamped/ped/main/files/43507162-41c3-4c33-af84-6bc8f2b905a9.png)

The above command should give an error message but it did not(?). Also, if the app supports this functionality, it should be sorted according to the amount first since f/a is inputted first(?)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: willyamped/ped#9

**Comment by lwlshawn** [comment]
This is listed in the UG, only the **last** prefix is considered
