### ISSUE TITLE
[PE-D] marktask

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#206]
![Screenshot 2021-10-29 at 4.48.30 PM.png](https://raw.githubusercontent.com/willyamped/ped/main/files/5ae283cf-9f89-493c-94dd-592c12d51d62.png)

Perhaps marking an already marked task should show an error message?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: willyamped/ped#10

**Comment by ngchisern** [comment]
@lwlshawn could you do this for the mark order command as well? #220
