### ISSUE TITLE
[PE-D] Infinity total order

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#209]
Screenshot:

![image.png](https://raw.githubusercontent.com/muhammad-khair/ped/main/files/1f07da47-0b4d-44cf-8724-7c5013955734.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: muhammad-khair/ped#12

**Comment by ngchisern** [comment]
@AY2122S1-CS2103T-W08-3/developers What do you guys think are the reasonable upper bound for the order amount? Or do you guys have any better suggestions to solve this?

**Comment by lwlshawn** [comment]
I already set an upper bound of 1 billion, I forgot to link to this issue.
