### ISSUE TITLE
[PE-D] Doesn't handle addition of duplicate tasks 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#212]
Steps to replicate bug : 
1. addtask l/sew buttons onto blazer d/20 August 2021
2. addtask l/sew buttons onto blazer d/20 August 2021

Expected output : error saying task already exists in list

Actual output : 

![image.png](https://raw.githubusercontent.com/aishh12/ped/main/files/f648a974-8c28-4da3-937c-293d263d4c7a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aishh12/ped#7

**Comment by ngchisern** [comment]
similar to #116. Will be handled by @lwlshawn
