### ISSUE TITLE
[PE-D] Can a task exceed the deadline of their linked order deadline

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#224]
Screenshot:

![image.png](https://raw.githubusercontent.com/muhammad-khair/ped/main/files/1fdc92a6-1373-4124-9ca3-0584c358c0c3.png)

![image.png](https://raw.githubusercontent.com/muhammad-khair/ped/main/files/90a29106-a051-46bc-96c5-c4cddfe451e9.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: muhammad-khair/ped#18

**Comment by lwlshawn** [comment]
Add update to UG for people to use their brains
