### ISSUE TITLE
[PE-D] Unable to add a new client with same name but different attributes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W08-3/tp#227]
If a client share the same name but has different attributes the person is still considered as existing in the address book

![image.png](https://raw.githubusercontent.com/dt-td/ped/main/files/9315c59f-92b8-45fe-8b42-235d3003b16c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dt-td/ped#10

**Comment by ngchisern** [comment]
same as #190
