### ISSUE TITLE
Order of different dates are considered duplicated

### ISSUE THREAD

**Issue by GnohChengYi** [AY2122S1-CS2103T-W08-3/tp#279]
#### Steps to Reproduce:
1. Add 2 orders with different dates but other details remain the same

#### Expected

Both orders are added successfully.

#### Actual

When adding the second order, error message "This order already exists in the orderbook" is displayed.

This should not be the case because a client could order something multiple times on different dates.

#### Screenshot

![image](https://user-images.githubusercontent.com/19379090/140591962-f1136ca3-43ef-4d82-9f20-a046fd900f0b.png)

**Comment by ngchisern** [comment]
<img width="936" alt="Screenshot 2021-11-06 at 10 14 22 AM" src="https://user-images.githubusercontent.com/64767959/140594447-5dbc8c07-af29-47e3-be9a-3515fa0f03c7.png">
Mine works fine.

**Comment by ngchisern** [comment]
Not sure why @lwlshawn removed the date check in the isSameOrder() method. @lwlshawn, let me know if you have a particular reason for doing so.  I'll fix this issue.
