### ISSUE TITLE
AddOrder commend jumping number 

### ISSUE THREAD

**Issue by yuifuku1118** [AY2122S1-CS2103T-W08-3/tp#295]
I'm not sure if this is considered a bug, but small thing that noticed similar to the previous bug.
When I mistakenly put a wrong client name, then addorder again, the Sales order ID jumps by 1.

How to reproduce this:
1. Addorder with wrong client name (e.g. addorder l/School uniform c/No one a/10.90 d/20 August 2021)
2. Then add order again with correct name (e.g. addorder l/School uniform c/Alex Yeoh a/10.90 d/20 August 2021) 
<img width="1134" alt="maybe a bug" src="https://user-images.githubusercontent.com/65125272/140638810-2ccbe88d-4ba8-4a01-9d76-71ed4d0efb68.png">

**Comment by ngchisern** [comment]
I believe that @lwlshawn has already written the code to fix this during our last meeting, but it seems like he hasn't created the pr yet.
